# Generated by Django 3.0 on 2019-12-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва Телефону')),
                ('about', models.TextField()),
                ('diagonal', models.PositiveSmallIntegerField()),
                ('resolution', models.CharField(max_length=15)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('mah', models.IntegerField()),
                ('main_cam', models.PositiveSmallIntegerField()),
                ('front_cam', models.PositiveSmallIntegerField(default=None)),
                ('matrix', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кількість')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
