# Generated by Django 3.0 on 2019-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Назва Костюму')),
                ('about', models.TextField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
