# Generated by Django 3.0 on 2019-12-19 16:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191217_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
